test_video_path: ./input/08fd33_4.mp4
output_video_path: ./output/tracking_system_output.mp4
players_model_path: ./models/no_tactical_players_yolov8/weights/best.pt
keypoints_model_path: ./models/train_tv_keypoints_yolov8/weights/best.pt
tracking_cache_path: ./output/tracks_cache_4.pickle
keypoints_cache_path: ./output/keypoints_cache_4.pickle




